// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-central-1",
    "aws_content_delivery_bucket": "testamplify-20181207173158--hostingbucket",
    "aws_content_delivery_bucket_region": "eu-central-1",
    "aws_content_delivery_url": "http://testamplify-20181207173158--hostingbucket.s3-website.eu-central-1.amazonaws.com",
    "aws_appsync_graphqlEndpoint": "https://2d2d3gnyzjeddpnodvqtubq4lm.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-pubsva5y7zfrjk7pt5t3t5ofxy"
};


export default awsmobile;
